name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
permissions: 
  issues: write
  contents: write
  pull-requests: write
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commands: example
